// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newgitchanges23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newgitchanges23));
        
        string IMigrationMetadata.Id
        {
            get { return "202112281127092_newgitchanges23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
